### ISSUE TITLE
Validation of various text fields throughout the project.

### ISSUE THREAD

**Issue by free4murad** [BuildmLearn/BuildmLearn-Toolkit-Android#220] opened 2016-11-11 01:01 UTC
Many text field throughout the project can be left blank by just typing spaces in the text fields.
The user instead of name, questions, options etc can type in a couple of spaces and leave the text fields empty. This issue is in every template. (Some screen shots attached.)

(Info Template)
![image](https://cloud.githubusercontent.com/assets/17262180/20200569/efeb275e-a7d7-11e6-94ee-f2616ac12372.png)

(Match Template)
![match template](https://cloud.githubusercontent.com/assets/17262180/20200260/388c4cb0-a7d6-11e6-94c7-df5b33dafeb4.png)
(Dictation template)
![dictation template](https://cloud.githubusercontent.com/assets/17262180/20200271/4817ceb6-a7d6-11e6-89c1-960aea27ac16.png)
(Quiz Template)
![quiz template](https://cloud.githubusercontent.com/assets/17262180/20200278/5553701c-a7d6-11e6-9018-e6e33ea39133.png)
(Comprehention Template)
![comprehention template](https://cloud.githubusercontent.com/assets/17262180/20200286/64ba2faa-a7d6-11e6-8b1d-5beb65259287.png)
______________________________________________________________________________________________
Text field "User Name" On FirstRunActivity and in SettingsFragment has the same issue.

(SettingsFragment) (Typing spaces in your name)
![settings 1](https://cloud.githubusercontent.com/assets/17262180/20200460/5b6cb5d4-a7d7-11e6-98fb-75915ba3126e.png)
(SettingsFragment) (The field accepts just spaces and hence its blank.)
![settings 2](https://cloud.githubusercontent.com/assets/17262180/20200500/87d9015e-a7d7-11e6-8a69-9d0d20af8177.png)

These text fields must not be empty.

**Comment by free4murad** [comment] 2016-11-11 01:03
Can I make a PR for this issue?

**Comment by free4murad** [comment] 2016-11-11 07:00
Just made a PR.
#222

**Comment by croozeus** [comment] 2016-11-11 07:01
@free4murad thanks! @opticod will review and merge as he gets time.

**Comment by codingblazer** [comment] 2016-11-11 07:36
@opticod This is a duplicate issue of #216 of which I already sent the PR #217.

**Comment by croozeus** [comment] 2016-11-11 07:42
@free4murad damn, can you make sure you cross check the existing issues before creating duplicates. I am closing this one, @opticod let's review the PR sent by @codingblazer

**Closed by croozeus** 2016-11-11 07:42 UTC

**Comment by free4murad** [comment] 2016-11-11 17:38
In PR #217 only UserName, Title and text field have been validated.
I have added code to validate question and answers as well.

**Comment by free4murad** [comment] 2016-11-11 17:57
@codingblazer you have validated text fields only in three activities 
1. FirstRunActivity.java
2. TemplateEditor.java
3. SettingsFragment.java
These changes only validate feilds like UserName, Title.

where as in PR #222 I have validated text fields of 8 extra activities, namely
1. ComprehensionTemplate.java
2. DictationTemplate.java
3. FlashTemplate.java
4. InfoTemplate.java
5. LearnSpellingTemplate.java
6. MatchTemplate.java
7. QuizTemplate.java
8. VideoCollectionTemplate.java
Here in addition to the feild you have validated I have also validated feilds like question, answer, hint, description, etc

**Comment by codingblazer** [comment] 2016-11-11 17:57
@free4murad In #216 , I already mentioned that the problem is in fields throughout the project and I am working on all of them. I even informed you of the same 3 days back in #219 .

**Comment by free4murad** [comment] 2016-11-11 18:03
@codingblazer  in #219 there is no mention of fields like question, answer etc

you just mentioned #216 and #217 where you have mentioned three fields. Mention of "problems in fields throughout the project" can not be found in neither #216 nor #217.

**Comment by codingblazer** [comment] 2016-11-11 18:14
@free4murad Just for reference 

> At many other places like in Template name,Author name **etc**

> at various fields in the project - in Issue Title

Sorry if I didn't write names of all 13 fields and their respective activities.
As for #219 (yours) which was exact same PR as mine #217 , I made a comment there in #219 informing you that I am still working on issue.

**Comment by codingblazer** [comment] 2016-11-11 18:19
@free4murad Let's not get into argument here. If maintainers find your PR fine while reviewing (without any bug) , they may merge it. It was not that big issue in terms of time spent by me. Thanks and let's work together.

**Comment by free4murad** [comment] 2016-11-11 18:36
@codingblazer the point is that you wrongly said that you have already mentioned the issue because of which @croozeus closed the issue. 

Nowhere in #216 did you mention fields like answers and questions. My issue was different from yours.

Anyway what's done is done.
Thanks and let's work together.

**Comment by opticod** [comment] 2016-11-29 13:08
@codingblazer, I reviewed your PR #217, please resolve merge conflicts. 

@free4murad, I also checked your PR #219. So can you please remove validations for Template name, Author name and Username (in Settings and FirstRunActivity) to check for empty string or string with non alphanumeric starting character which are addressed by PR#217? Then we can merge your rest of the validations.
