### ISSUE TITLE
backpress not working properly in simulator of video,dictation and flash templates

### ISSUE THREAD

**Issue by tejavojjala** [BuildmLearn/BuildmLearn-Toolkit-Android#314] opened 2016-12-20 16:39 UTC
Problems in Video and Dictation templates:<br>
            Create a project and run the simulator. Now select a video(or dictation). Click back press. You will be redirected to choose. Instead go to the last fragment and click restart. Now click back press. Instead of redirecting to choose you will be exited.<br>
Problems in flash card template:<br>
            Clicking backpress should take you to the previous card. Instead the app is exiting.

@opticod shall I create a pr for this?

**Comment by opticod** [comment] 2016-12-31 13:52
Case Video and Dictation templates: Once the user restarts,on clicking back press, it should not redirect to last fragment. Hence it looks fine to me.

But with flash card template, its an issue, while checking one card, on pressing back, it should redirect to last fragment for that card.

You can continue with fixing the 2nd one.

**Comment by iit2014086** [comment] 2016-12-31 15:29
@opticod after restart,on clicking back press i didn't mean last fragment, l am saying the very first fragment where the user is asked to choose from the list available.
Like say there are 2 different passages in a dictation project. Now if you choose the 1st and instead of submitting do backpress(not back button), you will again be redirected to first fragment and asked to choose one of the dictations. Now again choose 1st,submit it and restart. Now if you perform back press the app is exited instead of asking you to choose one of the dictations.

**Comment by opticod** [comment] 2017-01-13 14:08
@iit2014086 , yea my mistake. I checked it. Its not showing the very first fragment.

**Comment by opticod** [comment] 2017-01-14 09:35
@iit2014086, this issue is only with simulator or also with the created APKs?

**Comment by iit2014086** [comment] 2017-01-14 13:27
@opticod the issue is with the created APK's also. Shall I send a pr to toolkit-mobile-templates too?

**Comment by opticod** [comment] 2017-01-14 14:07
Yaa. First u create a PR there, and wait for it to get reviewed and merged. Then with those changes and updated master branch of Toolkit-mobile-templates, create those updated APKs and add it to PR targeted here.

**Comment by iit2014086** [comment] 2017-01-14 14:20
Okay. I will send a pr there ;)

**Comment by opticod** [comment] 2017-02-13 19:20
Closed via #394

**Closed by opticod** 2017-02-13 19:20 UTC
